### ISSUE TITLE
Where I can download modsettings FS17?

### ISSUE THREAD

**Issue by Vanquish081** [DeckerMMIV/FarmSim_Mod_Glance#16]
You are referenc in description of Glance, but I can't see link in any description for download modsettings.

**Comment by DeckerMMIV** [comment]
That is just a folder called `modsSettings` for now, so the config-file for Glance is not contaminating the `mods` or `savegave#` folders.

I have not yet attempted to try upgrade my FS15 'ModsSettings' mod to FS17.

**Comment by Vanquish081** [comment]
Ok, I have this dude... ;)
