### ISSUE TITLE
Support for greenhouse salad

### ISSUE THREAD

**Issue by Dzi4d3k** [DeckerMMIV/FarmSim_Mod_Glance#6]
Hi,

Is it possible to add support for greenhouse with salad from:
http://marhu.net/phpBB3/viewtopic.php?f=140&t=2315
like it was added for lumbermill?

**Comment by DeckerMMIV** [comment]
Maybe. If I could get hold of that mod, from a site that have no download-speed restrictions (_I do not like uploaded.to_)

**Comment by Dzi4d3k** [comment]
Here is fast mirror:
http://www.modhub.us/farming-simulator-2015-mods/greenhouse-salad-v1-21/
