### ISSUE TITLE
Krone Ultima- mod contest

### ISSUE THREAD

**Issue by jhomer** [DeckerMMIV/FarmSim_Mod_Glance#8]
Hey Decker,
I was trying some different stuff on your glance mod to get the net wrap amount to show in glance.
There is the extension mod that shows it in a display while operating but I was trying to get it to show one step further on "glance".  The extension- http://marhu.net/phpBB3/viewtopic.php?f=141&t=3332

I'm sure there's probably a lot more to it than what I think.
And I don't have too much of a clue of what I'm doing.
In your opinion, would this be a few extra lines of code or shall I just pull the plug?

My coding knowledge consists of doing quite a few different codes for Arduino- (the programming for dummies)
The only successful thing I could make "glance" do different was to "NOT work at all"!
These LUA's just don't make sense to me and they don't seem to be very "self taught" friendly.

**Comment by DeckerMMIV** [comment]
Uhm, yeah. Glance's LUA-script isn't exactly "beautiful and clean code" :pensive:

I have not yet actually really tried that Krone Ultima in-game, so there may be stuff I'm ignorant of.

So the thing you are looking for, is that Glance shows the calculated `numLeftBalesNet` and `numLeftBalesFoil` in a particular column of Glance's rendered lines? Maybe the same line as the vehicle pulling the Krone Ultima?

I will try to see what I can add to the script, regarding this particular baler.

**Comment by DeckerMMIV** [comment]
Okay, I've added some code to just display the remaining foils & netwraps of the Krone Ultima CF155XC.

If you, in your Glance_Config.XML, add `BalerNumFoilsNets` to one of the <vehiclesColumnOrder> columns, then it should show the information, using the v2.4.5 of Glance.

```
<column enabled="true" contains="ActiveTask;EngineOn;BalerNumFoilsNets" align="left" minWidthText="" />
```

**Comment by jhomer** [comment]
Have tested and works great!!! Update's as it should.
I could have tried for weeks and still not gotten it to work (other than make stuff not work at all).
I guess it pays to know what your doing!!!
These LUA's are just to far above my competence level.

This is not really an issue but I thought you'd like to know anyway:
Glance does not seem to know that the Ultima is a baler.
It seems to know what is in the baler but just not that it's a baler.
This is also the same for courseplay- you get the message- "wrong tool for this mode".

Thanks for your work of adding this in!!!
I spend most time with the huds hidden and glance on.
