### ISSUE TITLE
FS17 upgrade?

### ISSUE THREAD

**Issue by DeckerMMIV** [DeckerMMIV/FarmSim_Mod_Glance#9]
Your question: Is this going to be upgraded to FS17?

My answer: When I get annoyed enough of not knowing what my hired workers are doing, then I will look into upgrading Glance to FS17.

**Comment by Gonimy-Vetrom** [comment]
I'm really looking forward to. Without it, it is not convenient to play.

**Comment by Dzi4d3k** [comment]
Hire workers are just small part, our team on MP feel lost without Glance...

**Comment by mereman** [comment]
Another who wants to see Glance for FS17. I much prefer Glance to the other mod.

**Comment by Vanquish081** [comment]
The mean function is for multiplayer.

**Comment by DeckerMMIV** [comment]
I have started upgrading it.

**Comment by TheRealestMcCoy** [comment]
How is the mod coming along?

**Comment by DeckerMMIV** [comment]
It is still being slowly worked on. - Due to some thing called 'real life' :wink:, I can't/won't spend my entire sparetime on just doing upgrading.

**Comment by DeckerMMIV** [comment]
Almost ready for release. - Have uploaded ONLY the `ModDesc_l10n_<language-code>.XML` files, if anyone wants to contribute some proper translations for their language, before I create an actual release for ModHub.

**Comment by Vanquish081** [comment]
Here in spanish (Spain)

http://pastebin.com/jtHDL7Nf

**Comment by DeckerMMIV** [comment]
Now uploading to ModHub - then awaiting what GIANTS' ModHub team decides of; accept or reject.

**Comment by Vanquish081** [comment]
Well, you can share here for your fans xD

**Comment by Gonimy-Vetrom** [comment]
Hooray!!! Release.

**Comment by Gonimy-Vetrom** [comment]
version 1.0.0.32? It's how much work had to remake?

**Comment by DeckerMMIV** [comment]
@Gonimy-Vetrom - I have been working on the code in a non-published branch `FS2017`, so you can not really take the "version number" as an indication of how much have been changed.

The FS17 code of Glance have now been merged into the `master` branch. - There may be some change-notes I have missed.

**Comment by mereman** [comment]
Really happy to have Glance back. Thanks Decker

**Comment by DeckerMMIV** [comment]
Closing this issue. Any bugs/problems/suggestions should be created in new individual issues.
